### ISSUE TITLE
Error: Coin or token type undefined not supported

### ISSUE THREAD

**Issue by arruah** [BitGo/bitgo-cli-v2#1]
When I run ./bin/bgo user wallets
I got the error 
Error: Coin or token type undefined not supported

OS: Ubuntu 16.04
npm -v 
5.8.0
node -v
9.9.0

**Comment by zacleids** [comment]
Hi @arruah, just wanted to confirm that you logged into the tool using `bgo login`, and that you set the v2 coin of the wallets you wanted to list like `bgo coin btc`. If you did not, please try that and let us know if it works. If you did, please copy and paste the whole error message.

**Comment by zacleids** [comment]
closing due to non response

**Comment by anuraggupta816** [comment]
I am facing the same issue and details as follows.
bitgo version:11.11.1
node version:11.4.0

 initializeBitGo error:  Error: Coin or token type ttron not supported or not compiled. Please be sure that you are using the latest version of BitGoJS.
